// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvuvjynjgzakigvfyrjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2dXZqeW5qZ3pha2lndmZ5cmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTk2ODksImV4cCI6MjA2NDI3NTY4OX0.OBrWhzdG3Jws_oe4jMQ-GZxXzDXcOlkkezkXyAuGbTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);